### ISSUE TITLE
Manage error handling better when Fold download fails

### ISSUE THREAD

**Issue by marc-vdm** [polca/ScenarioLink#10]
Just got this error when trying to download a new Fold.

```python
Cache folder:  C:\Users\meidemtvander\AppData\Local\ActivityBrowser\ActivityBrowser\Cache
Fetching data from Zenodo: https://zenodo.org/api/records/8353213
Downloading file 1/1
Traceback (most recent call last):
  File "C:\Users\meidemtvander\.conda\envs\scenariolink\lib\site-packages\urllib3\response.py", line 444, in _error_catcher
    yield
  File "C:\Users\meidemtvander\.conda\envs\scenariolink\lib\site-packages\urllib3\response.py", line 567, in read
    data = self._fp_read(amt) if not fp_closed else b""
  File "C:\Users\meidemtvander\.conda\envs\scenariolink\lib\site-packages\urllib3\response.py", line 533, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
  File "C:\Users\meidemtvander\.conda\envs\scenariolink\lib\http\client.py", line 463, in read
    n = self.readinto(b)
  File "C:\Users\meidemtvander\.conda\envs\scenariolink\lib\http\client.py", line 507, in readinto
    n = self.fp.readinto(b)
  File "C:\Users\meidemtvander\.conda\envs\scenariolink\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\meidemtvander\.conda\envs\scenariolink\lib\ssl.py", line 1275, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\meidemtvander\.conda\envs\scenariolink\lib\ssl.py", line 1133, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\meidemtvander\.conda\envs\scenariolink\lib\site-packages\requests\models.py", line 816, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "C:\Users\meidemtvander\.conda\envs\scenariolink\lib\site-packages\urllib3\response.py", line 628, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\Users\meidemtvander\.conda\envs\scenariolink\lib\site-packages\urllib3\response.py", line 593, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "C:\Users\meidemtvander\.conda\envs\scenariolink\lib\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\meidemtvander\.conda\envs\scenariolink\lib\site-packages\urllib3\response.py", line 449, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='zenodo.org', port=443): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\meidemtvander\pycharmprojects\scenariolink\ab_plugin_scenariolink\tables\models.py", line 125, in get_datapackage_from_record
    dp = download_files_from_zenodo(dp_name)
  File "c:\users\meidemtvander\pycharmprojects\scenariolink\ab_plugin_scenariolink\utils.py", line 99, in download_files_from_zenodo
    response = requests.get(file_url, timeout=10)
  File "C:\Users\meidemtvander\.conda\envs\scenariolink\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\Users\meidemtvander\.conda\envs\scenariolink\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\meidemtvander\.conda\envs\scenariolink\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\meidemtvander\.conda\envs\scenariolink\lib\site-packages\requests\sessions.py", line 747, in send
    r.content
  File "C:\Users\meidemtvander\.conda\envs\scenariolink\lib\site-packages\requests\models.py", line 899, in content
    self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
  File "C:\Users\meidemtvander\.conda\envs\scenariolink\lib\site-packages\requests\models.py", line 822, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='zenodo.org', port=443): Read timed out.
```

**Comment by romainsacchi** [comment]
Yep. A popup inviting to click on the button again would help.
