### ISSUE TITLE
release broken: requirements are not installed

### ISSUE THREAD

**Issue by marc-vdm** [polca/ScenarioLink#13]
I just tried installing from `-c romainsacchi` and it installed fine, but it didn't install requirements (`unfold`):

```shell
(ab_scenariolink) C:\>conda install -c romainsacchi ab-plugin-scenariolink
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 22.9.0
  latest version: 23.7.4

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: C:\Users\meidemtvander\.conda\envs\ab_scenariolink

  added / updated specs:
    - ab-plugin-scenariolink


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ab-plugin-scenariolink-0.0.1|                0          20 KB  romainsacchi
    ------------------------------------------------------------
                                           Total:          20 KB

The following NEW packages will be INSTALLED:

  ab-plugin-scenari~ romainsacchi/noarch::ab-plugin-scenariolink-0.0.1-0 None


Proceed ([y]/n)? y


Downloading and Extracting Packages
ab-plugin-scenarioli | 20 KB     | ############################################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Retrieving notices: ...working... done

(ab_scenariolink) C:\>activity-browser
-hiding tab:History

DevTools listening on ws://127.0.0.1:3999/devtools/browser/8619351d-daf5-4115-86dc-4cb47fd3ee49
-hiding tab:Activity Details
-hiding tab:Characterization Factors
-hiding tab:Graph Explorer
-hiding tab:LCA results
The Activity-Browser log file can be found at C:\Users\meidemtvander\AppData\Local\ActivityBrowser\ActivityBrowser\Logs/ab_logs-19_9_2023-8_6_12.log
Importing plugin ab_plugin_scenariolink
Error: Import of plugin ab_plugin_scenariolink failed
No module named 'unfold'
Traceback (most recent call last):
  File "C:\Users\meidemtvander\.conda\envs\ab_scenariolink\lib\site-packages\activity_browser\controllers\plugin.py", line 57, in load_plugin
    plugin_lib = importlib.import_module(name)
  File "C:\Users\meidemtvander\.conda\envs\ab_scenariolink\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\meidemtvander\.conda\envs\ab_scenariolink\lib\site-packages\ab_plugin_scenariolink\__init__.py", line 3, in <module>
    from .layouts.tabs import RightTab
  File "C:\Users\meidemtvander\.conda\envs\ab_scenariolink\Lib\site-packages\shiboken2\files.dir\shibokensupport\feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\meidemtvander\.conda\envs\ab_scenariolink\lib\site-packages\ab_plugin_scenariolink\layouts\tabs\__init__.py", line 1, in <module>
    from .right import RightTab
  File "C:\Users\meidemtvander\.conda\envs\ab_scenariolink\Lib\site-packages\shiboken2\files.dir\shibokensupport\feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\meidemtvander\.conda\envs\ab_scenariolink\lib\site-packages\ab_plugin_scenariolink\layouts\tabs\right.py", line 11, in <module>
    from ...tables.tables import FoldsTable, DataPackageTable
  File "C:\Users\meidemtvander\.conda\envs\ab_scenariolink\Lib\site-packages\shiboken2\files.dir\shibokensupport\feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\meidemtvander\.conda\envs\ab_scenariolink\lib\site-packages\ab_plugin_scenariolink\tables\tables.py", line 11, in <module>
    from .models import FoldsModel, DataPackageModel
  File "C:\Users\meidemtvander\.conda\envs\ab_scenariolink\Lib\site-packages\shiboken2\files.dir\shibokensupport\feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\meidemtvander\.conda\envs\ab_scenariolink\lib\site-packages\ab_plugin_scenariolink\tables\models.py", line 10, in <module>
    from ..utils import download_files_from_zenodo, package_from_path
  File "C:\Users\meidemtvander\.conda\envs\ab_scenariolink\Lib\site-packages\shiboken2\files.dir\shibokensupport\feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\meidemtvander\.conda\envs\ab_scenariolink\lib\site-packages\ab_plugin_scenariolink\utils.py", line 10, in <module>
    from unfold import Unfold
  File "C:\Users\meidemtvander\.conda\envs\ab_scenariolink\Lib\site-packages\shiboken2\files.dir\shibokensupport\feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'unfold'
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\meidemtvander\.conda\envs\ab_scenariolink\lib\site-packages\activity_browser\controllers\plugin.py", line 57, in load_plugin
    plugin_lib = importlib.import_module(name)
  File "C:\Users\meidemtvander\.conda\envs\ab_scenariolink\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\meidemtvander\.conda\envs\ab_scenariolink\lib\site-packages\ab_plugin_scenariolink\__init__.py", line 3, in <module>
    from .layouts.tabs import RightTab
  File "C:\Users\meidemtvander\.conda\envs\ab_scenariolink\Lib\site-packages\shiboken2\files.dir\shibokensupport\feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\meidemtvander\.conda\envs\ab_scenariolink\lib\site-packages\ab_plugin_scenariolink\layouts\tabs\__init__.py", line 1, in <module>
    from .right import RightTab
  File "C:\Users\meidemtvander\.conda\envs\ab_scenariolink\Lib\site-packages\shiboken2\files.dir\shibokensupport\feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\meidemtvander\.conda\envs\ab_scenariolink\lib\site-packages\ab_plugin_scenariolink\layouts\tabs\right.py", line 11, in <module>
    from ...tables.tables import FoldsTable, DataPackageTable
  File "C:\Users\meidemtvander\.conda\envs\ab_scenariolink\Lib\site-packages\shiboken2\files.dir\shibokensupport\feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\meidemtvander\.conda\envs\ab_scenariolink\lib\site-packages\ab_plugin_scenariolink\tables\tables.py", line 11, in <module>
    from .models import FoldsModel, DataPackageModel
  File "C:\Users\meidemtvander\.conda\envs\ab_scenariolink\Lib\site-packages\shiboken2\files.dir\shibokensupport\feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\meidemtvander\.conda\envs\ab_scenariolink\lib\site-packages\ab_plugin_scenariolink\tables\models.py", line 10, in <module>
    from ..utils import download_files_from_zenodo, package_from_path
  File "C:\Users\meidemtvander\.conda\envs\ab_scenariolink\Lib\site-packages\shiboken2\files.dir\shibokensupport\feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\meidemtvander\.conda\envs\ab_scenariolink\lib\site-packages\ab_plugin_scenariolink\utils.py", line 10, in <module>
    from unfold import Unfold
  File "C:\Users\meidemtvander\.conda\envs\ab_scenariolink\Lib\site-packages\shiboken2\files.dir\shibokensupport\feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'unfold'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\meidemtvander\.conda\envs\ab_scenariolink\lib\logging\__init__.py", line 434, in format
    return self._format(record)
  File "C:\Users\meidemtvander\.conda\envs\ab_scenariolink\lib\logging\__init__.py", line 430, in _format
    return self._fmt % record.__dict__
KeyError: 'ABmodule'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\meidemtvander\.conda\envs\ab_scenariolink\lib\logging\__init__.py", line 1083, in emit
    msg = self.format(record)
  File "C:\Users\meidemtvander\.conda\envs\ab_scenariolink\lib\logging\__init__.py", line 927, in format
    return fmt.format(record)
  File "C:\Users\meidemtvander\.conda\envs\ab_scenariolink\lib\logging\__init__.py", line 666, in format
    s = self.formatMessage(record)
  File "C:\Users\meidemtvander\.conda\envs\ab_scenariolink\lib\logging\__init__.py", line 635, in formatMessage
    return self._style.format(record)
  File "C:\Users\meidemtvander\.conda\envs\ab_scenariolink\lib\logging\__init__.py", line 436, in format
    raise ValueError('Formatting field not found in record: %s' % e)
ValueError: Formatting field not found in record: 'ABmodule'
Call stack:
  File "C:\Users\meidemtvander\.conda\envs\ab_scenariolink\Scripts\activity-browser-script.py", line 9, in <module>
    sys.exit(run_activity_browser())
  File "C:\Users\meidemtvander\.conda\envs\ab_scenariolink\lib\site-packages\activity_browser\__init__.py", line 46, in run_activity_browser
    application = Application()
  File "C:\Users\meidemtvander\.conda\envs\ab_scenariolink\lib\site-packages\activity_browser\application.py", line 24, in __init__
    setattr(self, attr, controller(self.main_window))
  File "C:\Users\meidemtvander\.conda\envs\ab_scenariolink\lib\site-packages\activity_browser\controllers\plugin.py", line 29, in __init__
    self.load_plugins()
  File "C:\Users\meidemtvander\.conda\envs\ab_scenariolink\lib\site-packages\activity_browser\controllers\plugin.py", line 45, in load_plugins
    self.plugins[name] = self.load_plugin(name)
  File "C:\Users\meidemtvander\.conda\envs\ab_scenariolink\lib\site-packages\activity_browser\controllers\plugin.py", line 61, in load_plugin
    log.error("Error: Import of plugin {} failed".format(name), error=e)
  File "C:\Users\meidemtvander\.conda\envs\ab_scenariolink\lib\site-packages\activity_browser\logger.py", line 141, in error
    ABHandler.log.error(kwargs['error'], exc_info=exc_info)
Message: ModuleNotFoundError("No module named 'unfold'")
Arguments: ()
Loading user settings:
dirpath already loaded
Reset project settings directory to:C:\Users\meidemtvander\AppData\Local\pylca\Brightway3\ei39.f1469ad5eb0a071dc60323f6e0fce980
Traceback (most recent call last):
  File "C:\Users\meidemtvander\.conda\envs\ab_scenariolink\lib\site-packages\activity_browser\controllers\plugin.py", line 97, in reload_plugins
    self.close_plugin_tabs(self.plugins[name])
  File "C:\Users\meidemtvander\.conda\envs\ab_scenariolink\lib\site-packages\activity_browser\controllers\plugin.py", line 90, in close_plugin_tabs
    panel.close_tab_by_tab_name(plugin.infos["name"])
AttributeError: 'NoneType' object has no attribute 'infos'
Loaded project:ei39
Brightway2 data directory: C:\Users\meidemtvander\AppData\Local\pylca\Brightway3
Brightway2 active project: ei39
Qt Version:5.15.8
Remote debugging server started successfully. Try pointing a Chromium-based browser to http://127.0.0.1:3999

```

**Comment by romainsacchi** [comment]
I know, I forgot to specify some libraries under "run" of meta.yaml

**Comment by romainsacchi** [comment]
Fixed. Released on anaconda https://anaconda.org/romainsacchi/ab-plugin-scenariolink
