### ISSUE TITLE
downloading zips broken

### ISSUE THREAD

**Issue by marc-vdm** [polca/ScenarioLink#14]
```python
Cache folder:  C:\Users\meidemtvander\AppData\Local\ActivityBrowser\ActivityBrowser\Cache
Fetching data from Zenodo: https://zenodo.org/api/records/
Traceback (most recent call last):
  File "c:\users\meidemtvander\pycharmprojects\scenariolink\ab_plugin_scenariolink\tables\models.py", line 131, in get_datapackage_from_record
    dp = download_files_from_zenodo(dp_name)
  File "c:\users\meidemtvander\pycharmprojects\scenariolink\ab_plugin_scenariolink\utils.py", line 102, in download_files_from_zenodo
    for idx, file_info in enumerate(json_data['files']):
KeyError: 'files'
```

**Comment by marc-vdm** [comment]
The downloader creates a 1kb file named `.zip` (so empty string?)

**Comment by marc-vdm** [comment]
I get the same error for cached files btw

**Comment by romainsacchi** [comment]
From your error, I can see that the record number is not fetched.
Is it because the column is hidden?

````
Fetching data from Zenodo: https://zenodo.org/api/records/
````

**Comment by marc-vdm** [comment]
I'll have a look, I probably broke this in my push then
