### ISSUE TITLE
Folds downloads fail

### ISSUE THREAD

**Issue by marc-vdm** [polca/ScenarioLink#26]
A user from the pLCA course) has the following issue. I tried and have the same issue.

This happens when trying to download the fold zips. I got a few timeouts (and could retry), when it finally worked, it failed again and I get a 1kb zip.

```python
(scenariolink) C:\>activity-browser
-hiding tab:History

DevTools listening on ws://127.0.0.1:3999/devtools/browser/c5672f55-04fa-4189-805c-3fda868b438a
-hiding tab:Activity Details
-hiding tab:Characterization Factors
-hiding tab:Graph Explorer
-hiding tab:LCA results
The Activity-Browser log file can be found at C:\Users\meidemtvander\AppData\Local\ActivityBrowser\ActivityBrowser\Logs/ab_logs-13_10_2023-14_32_44.log
Importing plugin ab_plugin_scenariolink
Loading user settings:
dirpath already loaded
Reset project settings directory to:C:\Users\meidemtvander\AppData\Local\pylca\Brightway3\default.c21f969b5f03d33d43e04f8f136e7682
Loaded tab ab_plugin_scenariolink
Loaded project:default
Brightway2 data directory: C:\Users\meidemtvander\AppData\Local\pylca\Brightway3
Brightway2 active project: default
Qt Version:5.15.8
Remote debugging server started successfully. Try pointing a Chromium-based browser to http://127.0.0.1:3999
Cache folder:  C:\Users\meidemtvander\AppData\Local\ActivityBrowser\ActivityBrowser\Cache
Fetching data from Zenodo: https://zenodo.org/api/records/8420334
Failed to get data from Zenodo. Error: HTTPSConnectionPool(host='zenodo.org', port=443): Read timed out. (read timeout=10)
Cache folder:  C:\Users\meidemtvander\AppData\Local\ActivityBrowser\ActivityBrowser\Cache
Fetching data from Zenodo: https://zenodo.org/api/records/8420334
Failed to get data from Zenodo. Error: HTTPSConnectionPool(host='zenodo.org', port=443): Read timed out. (read timeout=10)
Cache folder:  C:\Users\meidemtvander\AppData\Local\ActivityBrowser\ActivityBrowser\Cache
Fetching data from Zenodo: https://zenodo.org/api/records/8420334
Failed to get data from Zenodo. Error: HTTPSConnectionPool(host='zenodo.org', port=443): Read timed out. (read timeout=10)
Cache folder:  C:\Users\meidemtvander\AppData\Local\ActivityBrowser\ActivityBrowser\Cache
Fetching data from Zenodo: https://zenodo.org/api/records/8420334
Failed to get data from Zenodo. Error: HTTPSConnectionPool(host='zenodo.org', port=443): Read timed out. (read timeout=10)
Cache folder:  C:\Users\meidemtvander\AppData\Local\ActivityBrowser\ActivityBrowser\Cache
Fetching data from Zenodo: https://zenodo.org/api/records/8420334
Downloading file 1/1
Traceback (most recent call last):
  File "C:\Users\meidemtvander\.conda\envs\scenariolink\lib\site-packages\urllib3\connectionpool.py", line 466, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\meidemtvander\.conda\envs\scenariolink\lib\site-packages\urllib3\connectionpool.py", line 461, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\meidemtvander\.conda\envs\scenariolink\lib\http\client.py", line 1377, in getresponse
    response.begin()
  File "C:\Users\meidemtvander\.conda\envs\scenariolink\lib\http\client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "C:\Users\meidemtvander\.conda\envs\scenariolink\lib\http\client.py", line 281, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\meidemtvander\.conda\envs\scenariolink\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\meidemtvander\.conda\envs\scenariolink\lib\ssl.py", line 1275, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\meidemtvander\.conda\envs\scenariolink\lib\ssl.py", line 1133, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\meidemtvander\.conda\envs\scenariolink\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "C:\Users\meidemtvander\.conda\envs\scenariolink\lib\site-packages\urllib3\connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "C:\Users\meidemtvander\.conda\envs\scenariolink\lib\site-packages\urllib3\util\retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\meidemtvander\.conda\envs\scenariolink\lib\site-packages\urllib3\packages\six.py", line 770, in reraise
    raise value
  File "C:\Users\meidemtvander\.conda\envs\scenariolink\lib\site-packages\urllib3\connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\meidemtvander\.conda\envs\scenariolink\lib\site-packages\urllib3\connectionpool.py", line 468, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "C:\Users\meidemtvander\.conda\envs\scenariolink\lib\site-packages\urllib3\connectionpool.py", line 357, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='zenodo.org', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\meidemtvander\pycharmprojects\scenariolink\ab_plugin_scenariolink\utils.py", line 115, in download_files_from_zenodo
    response = requests.get(url, timeout=10)
  File "C:\Users\meidemtvander\.conda\envs\scenariolink\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\Users\meidemtvander\.conda\envs\scenariolink\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\meidemtvander\.conda\envs\scenariolink\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\meidemtvander\.conda\envs\scenariolink\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\meidemtvander\.conda\envs\scenariolink\lib\site-packages\requests\adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='zenodo.org', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\meidemtvander\pycharmprojects\scenariolink\ab_plugin_scenariolink\tables\models.py", line 146, in get_datapackage_from_record
    dp = download_files_from_zenodo(dp_name)
  File "c:\users\meidemtvander\pycharmprojects\scenariolink\ab_plugin_scenariolink\utils.py", line 118, in download_files_from_zenodo
    return retry_dialog()
  File "c:\users\meidemtvander\pycharmprojects\scenariolink\ab_plugin_scenariolink\utils.py", line 89, in retry_dialog
    return download_files_from_zenodo(record_id)
  File "c:\users\meidemtvander\pycharmprojects\scenariolink\ab_plugin_scenariolink\utils.py", line 118, in download_files_from_zenodo
    return retry_dialog()
  File "c:\users\meidemtvander\pycharmprojects\scenariolink\ab_plugin_scenariolink\utils.py", line 89, in retry_dialog
    return download_files_from_zenodo(record_id)
  File "c:\users\meidemtvander\pycharmprojects\scenariolink\ab_plugin_scenariolink\utils.py", line 118, in download_files_from_zenodo
    return retry_dialog()
  File "c:\users\meidemtvander\pycharmprojects\scenariolink\ab_plugin_scenariolink\utils.py", line 89, in retry_dialog
    return download_files_from_zenodo(record_id)
  File "c:\users\meidemtvander\pycharmprojects\scenariolink\ab_plugin_scenariolink\utils.py", line 118, in download_files_from_zenodo
    return retry_dialog()
  File "c:\users\meidemtvander\pycharmprojects\scenariolink\ab_plugin_scenariolink\utils.py", line 89, in retry_dialog
    return download_files_from_zenodo(record_id)
  File "c:\users\meidemtvander\pycharmprojects\scenariolink\ab_plugin_scenariolink\utils.py", line 148, in download_files_from_zenodo
    with zipfile.ZipFile(downloaded_zip_path, 'r') as downloaded_zip:
  File "C:\Users\meidemtvander\.conda\envs\scenariolink\lib\zipfile.py", line 1266, in __init__
    self._RealGetContents()
  File "C:\Users\meidemtvander\.conda\envs\scenariolink\lib\zipfile.py", line 1333, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

**Comment by marc-vdm** [comment]
![image](https://github.com/polca/ScenarioLink/assets/34626062/0d68cb60-af9a-46e3-aab8-c446c1cd3fa6)

**Comment by romainsacchi** [comment]
OK, I will first try to increase the time-out limit, to see.

**Comment by marc-vdm** [comment]
Could it be that Zenodo has low API limits on downloading these files and we are already over-requesting the API with our course users?

**Comment by romainsacchi** [comment]
@marc-vdm is it me, or is Zenodo down?

**Comment by romainsacchi** [comment]
<img width="1227" alt="Screenshot 2023-10-13 at 15 41 49" src="https://github.com/polca/ScenarioLink/assets/22473067/ff2926f2-105a-4256-8afd-f8ef7cf626ca">

**Comment by marc-vdm** [comment]
Ah, then that's the problem right now (and hopefully the problem in its entirety). 

Lets see if that fixes the issue in a few hours/tomorrow :)

**Comment by romainsacchi** [comment]
<img width="962" alt="Screenshot 2023-10-13 at 15 55 25" src="https://github.com/polca/ScenarioLink/assets/22473067/cb8defb9-5946-47c2-a827-51f5b06a8d95">
OK, they just changed overnight the whole interface. Maybe that's why. I need to identify the new URL to fetch the files from.

**Comment by marc-vdm** [comment]
🥲

**Comment by romainsacchi** [comment]
Fixed.
