### ISSUE TITLE
Installing online datapackages fails

### ISSUE THREAD

**Issue by flaarmann1000** [polca/ScenarioLink#33]
```
Fetching data from Zenodo: https://zenodo.org/api/records/10254220/files
Downloading file 1/1
downloaded.zip:  10%|########6                                                                            | 26.8M/264M [12:15<1:48:36, 38.2kB/s]
File 1 verification failed. Deleting C:\Users\...\AppData\Local\Temp\tmpqka2x2_k\downloaded.zip.
Traceback (most recent call last):
  File "C:\Users\...\miniconda3\envs\ab\lib\site-packages\ab_plugin_scenariolink\tables\models.py", line 146, in get_datapackage_from_record
    dp = download_files_from_zenodo(dp_name)
  File "C:\Users\...\miniconda3\envs\ab\lib\site-packages\ab_plugin_scenariolink\utils.py", line 191, in download_files_from_zenodo
    os.remove(os.path.join(folder_name, zip_filename))
PermissionError: [WinError 32] Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird: 'C:\\Users\\...\\AppData\\Local\\ActivityBrowser\\ActivityBrowser\\Cache\\10254220.zip'
```

tried running as admin, didn't work. 

There's an empty zip file in the Cache Folder.

**Comment by romainsacchi** [comment]
Hi @flaarmann1000 this seems indeed to be related to administration.
Can you try to delete the empty zip file and try again?

**Comment by romainsacchi** [comment]
Hi @flaarmann1000 , any development on this issue?

**Comment by flaarmann1000** [comment]
> Hi @flaarmann1000 , any development on this issue?

Hi @romainsacchi, sorry for the late reply: I reinstalled and everything works fine now. Thanks!
